default_platform(:ios)

platform :ios do
  desc "Upload to TestFlight"
  lane :upload_testflight do |options|
    api_key = app_store_connect_api_key(
      key_id: options[:api_key_id],
      issuer_id: options[:api_key_issuer_id],
      key_filepath: options[:api_key_path],
    )

    pilot(
      api_key: api_key,
      ipa: options[:ipa_path] || "../build/ios/ipa/coflanet.ipa",
      skip_waiting_for_build_processing: true,
    )
  end
end
